<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>Tests</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\API\API.csproj" />
      <ProjectReference Include="..\TestAssemblyTarget\TestAssemblyTarget.csproj" />
    </ItemGroup>

    <ItemGroup>

      <!-- Nuget dependencies -->
      <PackageReference Include="Krafs.Publicizer" Version="2.3.0" />

    </ItemGroup>

    <ItemGroup>
      <Publicize Include="0Harmony" />
    </ItemGroup>

    <ItemGroup>
      <Using Include="System" />
    </ItemGroup>

  <Import Project="..\HarmonyReference.props" />
</Project>
